### ISSUE TITLE
Minimum RAM requirement ?

### ISSUE THREAD

**Issue by vandpurnama** [CachyOS/cachyos-calamares#1]
I just download and want to install  CachyOS but i little disappointing  that i can't install because my ram not enough i have 4GB installed of ram it's same as requirement but i can't install because my ram get reduced because of hardware reserved 

leacy@stella ~ $ grep MemTotal /proc/meminfo
MemTotal:        3811120 kB

![Screenshot from 2022-11-17 02-45-18](https://user-images.githubusercontent.com/33601181/202343825-be23e6e0-20b2-4216-8e1e-c0a9cceb5ec8.png)

at least please write in website minimum os requirement...

**Comment by ptr1337** [comment]
> I just download and want to install CachyOS but i little disappointing that i can't install because my ram not enough i have 4GB installed of ram it's same as requirement but i can't install because my ram get reduced because of hardware reserved
> 
> leacy@stella ~ $ grep MemTotal /proc/meminfo MemTotal: 3811120 kB
> 
> ![Screenshot from 2022-11-17 02-45-18](https://user-images.githubusercontent.com/33601181/202343825-be23e6e0-20b2-4216-8e1e-c0a9cceb5ec8.png)
> 
> at least please write in website minimum os requirement...

We have changed the minimum requirement with the next release, that will be on this weekend.
https://github.com/CachyOS/cachyos-calamares/commit/689261205419c4215f4e495d67ebc5fb2b65115b
I will write you here, as soon we have updated the ISO.

And the next time it would be better, to start the installer over `cachyos-hello` over the launch installer button.

I will write today a bit more about the installation process, also over the requirements.

**Comment by ptr1337** [comment]
Sorry, I missed to write you here.
The new ISO has been released and you can find it at sourceforge or at our mirros (if sourceforge is slow).
https://sourceforge.net/projects/cachyos-arch

https://mirror.cachyos.org/ISO
