### ISSUE TITLE
Failed to add #2 partition: Invalid argument: The last usable GPT sector is 503316446, but 503316449 is requested.

### ISSUE THREAD

**Issue by RubenKelevra** [CachyOS/cachyos-calamares#23]
**Describe the bug**
I want to install CachyOS in a virtual machine running in Vbox under Windows 11.

I've tried systemd-boot and grub as bootloaders, and then select a pretty typical installation on zfs, where the installer should create the necessary partitions.

Then an error popup shows up, telling me that there were insufficient space for creating the requested partitions - which makes no sense, as I told it to use all available space.

**To Reproduce**
1. Click through the installation, select automatic partitioning and zfs as filesystem
2. Click finish
3. See error

**Expected behavior**
Installation should continue until CachyOS is installed

**Screenshots and Logs**
https://termbin.com/70o1

**Comment by ptr1337** [comment]
ZFS requires a clean partition before being installed, see our wiki.

Also, the ZFS Installation works fine in Qemu and Native Systems, so I would suspect that this is an upstream calamares issue or kpmcore implementation.

**Comment by RubenKelevra** [comment]
What exactly do you mean by my partition being "not clean"?

The whole VM was just created — including the virtual hard drive.

**Comment by RubenKelevra** [comment]
Okay, I've created a new hard drive and started the VM again, to see if it's ZFS related - it's not.

If I select systemd-boot and ext4 as filesystem, the following error will show up:

```
Command: sfdisk --force --append /dev/sda

Failed to add partition ‘New Partition’ to device ‘/dev/sda’.
```

Full log:

https://termbin.com/cvx2

So you're saying calamares / kpmcore does not support VirtualBox installations and I should report this as a limitation upstream?

**Comment by ptr1337** [comment]
> What exactly do you mean by my partition being "not clean"?
> 
> The whole VM was just created — including the virtual hard drive.

kpmcore has problems on real hardware to format filesystem "x" and then to zfs. I mean a clean partition table.

> Okay, I've created a new hard drive and started the VM again, to see if it's ZFS related - it's not.

I can not reproduce this in QEMU still, either with testing ISO or release ISO.

Actually, maybe vmbox does create a weird partition before, which kpmcore is not able to format?
Maybe related:
https://forum.manjaro.org/t/manjaro-fails-to-create-partition/118358/4

**Comment by ptr1337** [comment]
If you can give me either a reproducer on real hardware or in qemu, i can try to debug it.

**Comment by RubenKelevra** [comment]
Okay, so I found the setting which causes it under VirtualBox: EFI - with BIOS it works fine.

Does it work fine with QEMU when it emulates EFI?

**Comment by ptr1337** [comment]
> Okay, so I found the setting which causes it under VirtualBox: EFI - with BIOS it works fine.
> 
> Does it work fine with QEMU when it emulates EFI?

Yes, I test to 95% with EFI in QEMU.

**Comment by SoulHarsh007** [comment]
https://github.com/CachyOS/cachyos-calamares/assets/57407752/db4987fd-82a8-416c-9e1e-2926f6557c48

Seems to work fine here on VirtualBox with EFI enabled, please try again with a Fresh VM.

**Comment by SoulHarsh007** [comment]
![image](https://github.com/CachyOS/cachyos-calamares/assets/57407752/c665686f-b1ef-455c-808d-409d3c435cdb)
![image](https://github.com/CachyOS/cachyos-calamares/assets/57407752/78421924-af62-46ee-bb50-4c648381b1e4)


just finished installing too!

**Comment by RubenKelevra** [comment]
Hey @SoulHarsh007,

as requested, I made a fresh VM and reproduced the issue:

https://drive.google.com/file/d/1Di1TddUxyHnwdGmzC7XA-DiKe0rvtD0X/view?usp=sharing

**Comment by RubenKelevra** [comment]
So will this issue be fixed or not?

**Comment by ptr1337** [comment]
We had a discussion in the discord about this and so far looking on it, this appears to be a configuration issue on your side. You should properly configure vbox.
I think @SoulHarsh007 did figure out, what exactly was wrong

Anyways, the partioning code is still upstream calamares and kpmcore, if you want to have it fixed, you should report the issue to them.
Additionally this issue is not reproduceable on barebones installation and hardware, qemu and vmware.

**Comment by SoulHarsh007** [comment]
Hello @RubenKelevra I was able to repro your exact issue when the virtual disk size is set to 240GO, but with smaller size like 32GO, the installation goes fine. I would recommend opening an issue at VirtualBox or kpmcore.

**Comment by RubenKelevra** [comment]
@ptr1337 wrote:
> You should properly configure vbox.

I have improperly configured vbox? Could you explain what that supposed to mean? I just installed it, added your ISO to a new VM, and it just doesn't work.

**Comment by ptr1337** [comment]
> @ptr1337 wrote:
> 
> > You should properly configure vbox.
> 
> I have improperly configured vbox? Could you explain what that supposed to mean? I just installed it, added your ISO to a new VM, and it just doesn't work.

SoulHarsh wrote you, what is happening. I wasnt sure, which configuration it was and it appears the size. as written above, since the paritioning is done by kpmcore you should create their a bugreport

**Comment by SoulHarsh007** [comment]
@RubenKelevra 
![image](https://github.com/CachyOS/cachyos-calamares/assets/57407752/6b614c79-42b8-46e2-96b6-90e01dfd4e3a)
I can confirm it happens with other distribution ISOs too, so it's not related to CachyOS, please consider opening a bug report upstream.

**Comment by RubenKelevra** [comment]
> please consider opening a bug report upstream.

I have no idea what to tell who exactly. So no, I won't report bugs in the software you use for you.

**Comment by RubenKelevra** [comment]
@SoulHarsh007 I don't see how that is funny. 

Pretty hostile communication style against newbies going on here. That's all I can see.

**Comment by ptr1337** [comment]
You can retry with the testing ISO, which contains calamares 3.3.8.
https://mirror.cachyos.org/ISO/testing/

There were some fixes for partioning

**Comment by RubenKelevra** [comment]
Thanks I'll try that :)

**Comment by RubenKelevra** [comment]
> You can retry with the testing ISO, which contains calamares 3.3.8. https://mirror.cachyos.org/ISO/testing/
> 
> There were some fixes for partioning

I've tried that under Linux with a VirtualBox (not Windows as before) and it works now with exactly the same settings.

So unless it's a Windows Version issue which does not occur when run under Linux, it's fixed now.

Thanks for the help!
