### ISSUE TITLE
Installation failled after reaching 100%,  with error '' The package manager could not make changes to the installed system. The command <pre>pacman</pre> returned error code 1. '' 

### ISSUE THREAD

**Issue by iHarryPotter178** [CachyOS/cachyos-calamares#26]
Tried to install cachyos twice, with Gnome desktop + systemd boot once and grub... Both times failed. 

**Describe the bug**
The error says 
'' The package manager could not make changes to the installed system. The command <pre>pacman</pre> returned error code 1. '' 

Tempbin: (https://termbin.com/pbe8)(url)
I don't know how long tempbin stays, it about 20 hours old. 

**To Reproduce** 
Just install normally on a x64v3 laptop. 
Note.. I installed the same iso before, but tested it and wanted to clean install now.

**Comment by ptr1337** [comment]
Mhm, that is weird. Actually, we have commited the fix yesterday already to the systemd/grub/ai branch:
https://github.com/CachyOS/cachyos-calamares/commit/19126595eb183c65c74424453bca7da7aad94702

Ill investigate.

**Comment by ptr1337** [comment]
Ohh, its 20 hours old. It has been fixed 13 hrs ago :)

**Comment by iHarryPotter178** [comment]
> Ohh, its 20 hours old. It has been fixed 13 hrs ago :)

I didn't have time then to report.. Glad to hear it's fixed.. I'll try installing again tomorrow.. Thanks for your hard work.
