### ISSUE TITLE
Error not letting me install CachyOS

### ISSUE THREAD

**Issue by Yaruze66** [CachyOS/cachyos-calamares#27]
**Describe the bug**
After starting the installation, literally after a minute I get an error and the installation fails.
```
error: archlinux-keyring: signature from "Christian Hesse <eworm@archlinux.org>" is unknown trust
error: failed to commit transaction (invalid or corrupted package (PGP signature))
```
I tried `sudo pacman -Sy archlinux-keyring` in Konsole as well as `sudo pacman-key --init`, `sudo pacman-key --populate` but it doesn't help.

I'm using newest KDE iso: `cachyos-kde-linux-240609.iso`

[tempbin](https://termbin.com/nfeq)

**To Reproduce**
Just a normal CachyOS installation without any additional conditions, after clicking on "Install" after about ~1 minute the installation returns error code 1.

**Comment by ptr1337** [comment]
> **Describe the bug** After starting the installation, literally after a minute I get an error and the installation fails.
> 
> ```
> error: archlinux-keyring: signature from "Christian Hesse <eworm@archlinux.org>" is unknown trust
> error: failed to commit transaction (invalid or corrupted package (PGP signature))
> ```
> 
> I tried `sudo pacman -Sy archlinux-keyring` in Konsole as well as `sudo pacman-key --init`, `sudo pacman-key --populate` but it doesn't help.
> 
> I'm using newest KDE iso: `cachyos-kde-linux-240609.iso`
> 
> [tempbin](https://termbin.com/nfeq)
> 
> **To Reproduce** Steps to reproduce the behavior: Just a normal CachyOS installation without any additional conditions, after clicking on "Install" after about ~1 minute the installation returns error code 1.

Hi Yaruze,

Yes, this is a problem either if a faulty mirror is used or somehow the keyring refresh is running from the wkd service.
Anyways, we have mitigates this for the upcoming releases, with:
1. Installing latest archlinux-keyring, before starting the installer
2. Only ranking Tier 1 Mirrors

You can find the testing ISO here:
https://mirror.cachyos.org/ISO/testing/

This is a german mirror, there is also us.cachyos.org, kr.cachyos.org, no.mirror.cx and co.
