### ISSUE TITLE
Customize LUKS options during install

### ISSUE THREAD

**Issue by ghost** [CachyOS/cachyos-calamares#35]
**Is your feature request related to a problem? Please describe.**
The default LUKS encryption options do not meet the needs of some use cases.

**Describe the solution you'd like**
Introduce a feature that allows users to specify their encryption preferences through a configuration file, luks_config.conf, which can be edited within the live environment. This would enable users to customize the default settings for cipher, key size, hash algorithm, PBKDF options, and header label according to their specific requirements.

**Describe alternatives you've considered**
Currently, there appears to be no option to modify the default LUKS settings used by the installer, which restricts users to a one-size-fits-all approach.

**Additional context**
Security researchers have differing opinions on the "most secure" configuration. Allowing informed users to customize their settings creates a more complex challenge for attackers, enhancing overall security.

**Comment by vnepogodin** [comment]
crypttab options can be changed in [src/modules/fstab/fstab.conf](https://github.com/calamares/calamares/blob/calamares/src/modules/fstab/fstab.conf#L12)

changing other encryption options cannot be changed that easily. for later open issue in the upstream please  (if not opened yet) https://github.com/calamares/calamares/issues
