### ISSUE TITLE
The package manager could not make changes to the installed system. The command <pre>pacman</pre> returned error code 1

### ISSUE THREAD

**Issue by FeyrisTan** [CachyOS/cachyos-calamares#38]
Up until now I've had my arch install with cachyos repos. Thought I'd check it out now.
However I get greeted with the error.
Spotted this during install - a bunch of 404 errors for these packages:

gcc
gcc-libs
glibc

**Comment by vnepogodin** [comment]
Hi, these errors related to gcc,gcc-libs,glibc are fine; it will just switch to another mirror.

anyways we need link to installer provided log

**Comment by FeyrisTan** [comment]
It was all I could see at the time since this is a retry. Whatever the issue was (I have pretty bad Internet) seems to have magically disappeared. Thanks for the very fast response!
