### ISSUE TITLE
failed to install if can not send query to raw.githubusercontent.com

### ISSUE THREAD

**Issue by him007** [CachyOS/cachyos-calamares#39]
someone falied to install because  rate-mirrors can't sent query to https://raw.githubusercontent.com/CachyOS/CachyOS-PKGBUILDS/master/cachyos-mirrorlist/cachyos-mirrorlist ,maybe DNS problem or something else.
i think `GitHub default,*.cachyos.org fallback` would be better.

see more :
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/cachyos-rate-mirrors/cachyos-rate-mirrors
https://github.com/CachyOS/cachyos-calamares/blob/cachyos-systemd-qt6/src/scripts/update-mirrorlist

![IMG_20241029_035539](https://github.com/user-attachments/assets/35709e98-9edf-4192-bfb3-811a8499e87f)

**Comment by vnepogodin** [comment]
that's issue with chinese ISP. fallback wont help much due to cloudflare being blocked AFAIR

**Comment by him007** [comment]
> that's issue with chinese ISP. fallback wont help much due to cloudflare being blocked AFAIR

no,cloudflare and cachyos are not being blocked.
