### ISSUE TITLE
Got `The package manager cannot make changes to an installed system`

### ISSUE THREAD

**Issue by Pinghigh** [CachyOS/cachyos-calamares#5]
**Describe the bug**
When I'm going to install CachyOS in a clean VMWare Virtual Machine, I got "
The package manager cannot make changes to an installed system"

**To Reproduce**
VM config: NVMe disk, VMware Paravirtual SCSI, UEFI boot, 12-core (intel CPU), USB 3.1 compatibility.

Install option: F2FS, systemd-boot, openbox+gnome package

**Expected behavior**
I got an error message "软件包管理器无法对已安装的系统进行更改", which means: "The package manager cannot make changes to an installed system".

**Screenshots and Logs**
https://termbin.com/l8czy

**Additional context**
I tried twice and got the same result. But I installed with the same config in Feb 2023 and succeeded.

**Comment by Pinghigh** [comment]
```log
target not found: ttf-nerd-fonts-symbols-1000-em
```

Since this package doesn't exist in the CachyOS repo/arch linux repo, I think you should remove this requirement.

**Comment by vnepogodin** [comment]
> **Describe the bug** When I'm going to install CachyOS in a clean VMWare Virtual Machine, I got " The package manager cannot make changes to an installed system"
> 
> **To Reproduce** VM config: NVMe disk, VMware Paravirtual SCSI, UEFI boot, 12-core (intel CPU), USB 3.1 compatibility.
> 
> Install option: F2FS, systemd-boot, openbox+gnome package
> 
> **Expected behavior** I got an error message "软件包管理器无法对已安装的系统进行更改", which means: "The package manager cannot make changes to an installed system".
> 
> **Screenshots and Logs** https://termbin.com/l8czy
> 
> **Additional context** I tried twice and got the same result. But I installed with the same config in Feb 2023 and succeeded.

Hi

yeah. it's due to arch did reverted their changes
Anyway we fixed that issue

Regards
