### ISSUE TITLE
ZFS Mirror Root Install

### ISSUE THREAD

**Issue by jakesteele** [CachyOS/cachyos-calamares#7]
**Is your feature request related to a problem? Please describe.**
I’d like to install my root OS on a mirror ZFS pool for speed and to handle single disk failure.

**Describe the solution you'd like**
During the installation process, I would like to be able to chose ZFS as the install, but pick multiple drives to install it onto.

**Describe alternatives you've considered**
None

**Additional context**
This is a pretty typical installation when following other guides to do a mirror pool for ZFS Root :D

**Comment by steff9488** [comment]
Are there any news regarding the support of a mirror root on zfs installation with cachyos? :)

**Comment by vnepogodin** [comment]
I think that should be closed here, and move to upstream. So far wasnt done any progress on that in upstream
