### ISSUE TITLE
Calamares to not select default device and btrfs subvolumes support

### ISSUE THREAD

**Issue by msmafra** [CachyOS/cachyos-calamares#9]
**Is your feature request related to a problem? Please describe.**
Calamares by default, at least on all distributions I tested that use it, automatically selects an installation device, BUT the field for that is, for lack of a better word, obscure. I, accidentally, formatted the wrong drive a few times.
I did not finish this test installation, since I did that mistake of formatting my games drive, so I'm not sure if this is implemented: BTRFS subvolmes support during install. Customizing them before installing.

**Describe the solution you'd like**
Not sure if Calamares allows that for that to be implemented, but, in my opinion, that shouldn't be the default nor it should be the so... small in the window.

**Describe alternatives you've considered**
If the field can be replaced/customised, showing the list of devices would be 'safer'. If not, at least not select a drive by default. Make the user select, is the safer route, in my opinion.

The default

![calamares-2024-01-01_22-20](https://github.com/CachyOS/cachyos-calamares/assets/1005457/71b23138-3b6c-424d-95d2-be74d3546df3)

Rough idea
![mockup](https://github.com/CachyOS/cachyos-calamares/assets/1005457/22986e4a-f36e-4ecc-ab76-713d35587409)

**Comment by vnepogodin** [comment]
this should be reported to upstream calamares
